//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoskaYkt_AutoManagement.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BrowserVisible {
            get {
                return ((bool)(this["BrowserVisible"]));
            }
            set {
                this["BrowserVisible"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int UnpublishDelayMinutes {
            get {
                return ((int)(this["UnpublishDelayMinutes"]));
            }
            set {
                this["UnpublishDelayMinutes"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RepublishDelayMinutes {
            get {
                return ((int)(this["RepublishDelayMinutes"]));
            }
            set {
                this["RepublishDelayMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideDriverWindow {
            get {
                return ((bool)(this["HideDriverWindow"]));
            }
            set {
                this["HideDriverWindow"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Title")]
        public string MyAdsSortBy {
            get {
                return ((string)(this["MyAdsSortBy"]));
            }
            set {
                this["MyAdsSortBy"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MyAdsSortAsc {
            get {
                return ((bool)(this["MyAdsSortAsc"]));
            }
            set {
                this["MyAdsSortAsc"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SchedulerStepSeconds {
            get {
                return ((int)(this["SchedulerStepSeconds"]));
            }
            set {
                this["SchedulerStepSeconds"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SchedulerUseJitter {
            get {
                return ((bool)(this["SchedulerUseJitter"]));
            }
            set {
                this["SchedulerUseJitter"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int SchedulerJitterMinSec {
            get {
                return ((int)(this["SchedulerJitterMinSec"]));
            }
            set {
                this["SchedulerJitterMinSec"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int SchedulerJitterMaxSec {
            get {
                return ((int)(this["SchedulerJitterMaxSec"]));
            }
            set {
                this["SchedulerJitterMaxSec"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int RepostDelayMinSec {
            get {
                return ((int)(this["RepostDelayMinSec"]));
            }
            set {
                this["RepostDelayMinSec"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int RepostDelayMaxSec {
            get {
                return ((int)(this["RepostDelayMaxSec"]));
            }
            set {
                this["RepostDelayMaxSec"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UsePlaywright {
            get {
                return ((bool)(this["UsePlaywright"]));
            }
            set {
                this["UsePlaywright"] = value;
            }
        }
    }
}
